FROM nvidia/cuda:11.3.1-base-ubuntu20.04

ENV TZ=Asia/Bangkok
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


RUN rm -f /etc/apt/sources.list.d/cuda.list \
    rm -f /etc/apt/sources.list.d/nvidia-ml.list \
    && apt-key del 7fa2af80 \
    && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
    && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub

RUN apt-get update

RUN apt install -y python3-pip

RUN apt-get install -y git
RUN apt-get install -y nano  locate  wget
RUN apt-get install -y libboost-python-dev libpython3.8-dev

#RUN pip3 install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118
RUN pip3 install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

# Set a working directory
WORKDIR /home/biplav/reid_train

# Copy your scripts into the container
#COPY ./supervisord.conf /app/docker/
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Set the default command to run when starting the container
CMD ["/bin/bash"]

# Expose port 5000 for MLflow and 8501 for Streamlit
#EXPOSE 5000 8501

#CMD ["/usr/bin/supervisord", "-c", "/app/docker/supervisord.conf"]